# Generated by Django 4.1.4 on 2022-12-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballerFinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('net_worth', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=5)),
                ('nationality', models.CharField(max_length=20)),
                ('other_professions', models.CharField(max_length=50)),
            ],
        ),
    ]
