# Generated by Django 4.1.4 on 2022-12-24 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('footballer_financial_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballerfinancialdata',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
