# Generated by Django 4.1.4 on 2022-12-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballer_financial_data', '0002_footballerfinancialdata_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballerfinancialdata',
            name='full_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
